### ISSUE TITLE
Fill image size automatically

### ISSUE THREAD

**Issue by JosefJezek** [tatsy/markdown-it-imsize#1]
Could you make option for fill image size automatically?

See algorithm from this atom package
https://github.com/minodisk/html-img

**Comment by tatsy** [comment]
Thanks for your request.

To fill image size itself is not very difficult, but I think there are a couple of choices to get image size on Node.
- [GraphicsMagick](http://aheckmann.github.io/gm/)
- [image-size](https://github.com/netroy/image-size)

For me, the second one seems better because it does not depend on ImageMagick or other CLI modules.

I will do it soon, so please wait for a moment.

**Comment by JosefJezek** [comment]
:+1:

**Comment by tatsy** [comment]
Done :+1:

**Comment by JosefJezek** [comment]
Thank you
