### ISSUE TITLE
looks like there is no bower package for it

### ISSUE THREAD

**Issue by Nedudi** [tatsy/markdown-it-imsize#2]
thank you for this plugin, I just found that

```
 bower ENOTFOUND     Package markdown-it-imsize not found
```

**Comment by tatsy** [comment]
@Nedudi Thank you for the message, I forgot to register the module to bower...

Now I have registered, and `bower install` works.

**Comment by Nedudi** [comment]
Thanks! But.. still looks like it does not work like other markdown-it-... plugins as AMD-module
I am using requirejs with other modules like markdown-it-sup, markdown-it-sup, markdown-it-mark,...
Thank you for your work, I migrated from marked to markdown-it, because it's mush more flexible.
I hope I can also take part doing few modules for markdown-it in near future

**Comment by tatsy** [comment]
@Nedudi I'm sorry to be late for the reply...

The problem was the dependency [image-size](https://github.com/netroy/image-size) of uses some dynamic require paths like the code below.

``` js
var libpath = process.env.TEST_COV ? '../lib-cov/' : './lib/';
var detector = require(libpath + 'detector');
```

because `browserify` cannot develop this kind of dynamic requires.

There are some choices to solve this problem, I think.
- To include whole `image-size` package to `markdown-it-imsize`
- Throw an issue to the authors of `image-size`

I 'm now trying to fix this problem, so please wait for a moment.

Sorry for your inconvenience...

**Comment by Nedudi** [comment]
Thanks a lot! That would be awesome

**Comment by tatsy** [comment]
Thank you for your waiting.

As long as I tested in my local environment, [`v1.1.4`](https://github.com/tatsy/markdown-it-imsize/releases/tag/v1.1.4) will work properly with RequireJS.

I added an example to use `markdown-it-imsize` with RequireJS in `README.md`.

Please refer it for the detail :smiley:
